/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_javaweb_jni_CommandExecution */

#ifndef _Included_org_javaweb_jni_CommandExecution
#define _Included_org_javaweb_jni_CommandExecution
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_javaweb_jni_CommandExecution
 * Method:    exec
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_javaweb_jni_CommandExecution_exec
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
