/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_jsp_test_jsp */

#ifndef _Included_org_apache_jsp_test_jsp
#define _Included_org_apache_jsp_test_jsp
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
